#use_frameworks!

platform :ios, '8.0'

target 'libopencore-amr-ios_Example' do
  pod 'libopencore-amr-ios', :path => '../'

  target 'libopencore-amr-ios_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
